spring:
  datasource:
        url: jdbc:mysql://localhost:3306/rentcloud_customer?createDatabaseIfNotExist=true
        username:
        password:
        driven-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
        naming:
            physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
        ddl-auto: none
